# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-datetime',),
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('progress', models.SmallIntegerField(blank=True, choices=[(None, '~'), (1, 'Finished'), (2, 'Dropped'), (3, 'Ongoing'), (4, 'Waiting')], null=True)),
                ('rating', models.SmallIntegerField(blank=True, choices=[(None, '~'), (0, '○○○○○ Terrible'), (1, '●○○○○ Poor'), (2, '●●○○○ Okay'), (3, '●●●○○ Good'), (4, '●●●●○ Great'), (5, '●●●●● Excellent')], null=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='tracker.Tag'),
        ),
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('title', 'date')]),
        ),
    ]
